# Generated by Django 5.0.1 on 2024-01-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avocat',
            name='selected_dates',
            field=models.TextField(blank=True),
        ),
    ]
