# Generated by Django 5.0.1 on 2024-01-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0002_avocat_selected_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='avocat',
            name='confirm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avocat',
            name='star',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avocat',
            name='cv',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
