# Generated by Django 5.0.1 on 2024-01-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0003_avocat_confirm_avocat_star_alter_avocat_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avocat',
            name='setSelectedOptions',
            field=models.TextField(blank=True),
        ),
    ]
