# Generated by Django 5.0.1 on 2024-01-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0003_avocat_confirm_avocat_star_alter_avocat_cv_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
