# Generated by Django 5.0.1 on 2024-01-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0005_alter_avocat_setselectedoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avocat',
            name='setSelectedOptions',
            field=models.JSONField(),
        ),
    ]
