# Generated by Django 5.0.1 on 2024-01-28 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0006_alter_avocat_setselectedoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('editeur_nom', models.CharField(max_length=50)),
                ('review_txt', models.TextField()),
                ('stars', models.IntegerField()),
                ('date_review', models.DateField()),
                ('heur', models.TimeField()),
                ('id_avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
