# Generated by Django 5.0.1 on 2024-01-28 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0007_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('description_cas', models.TextField(blank=True, null=True)),
                ('nom_prenom', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='review',
            old_name='heur',
            new_name='heure',
        ),
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id_rdv', models.AutoField(primary_key=True, serialize=False)),
                ('date_rdv', models.DateField(blank=True, null=True)),
                ('heure', models.TimeField(blank=True, null=True)),
                ('taken', models.BooleanField(blank=True, null=True)),
                ('id_avocat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyer.utilisateur')),
            ],
        ),
    ]
